name              = "sledujkikicom"   # slug viditelný v CF dashboardu
main              = "src/worker.js"
compatibility_date = "2025-06-30"

# pokud Worker obsluhuje celou subdoménu:
route = "www.sledujkiki.com/*"
[observability.logs]
enabled = true
