name              = "sledujkikicom"  # libovolné jméno
main              = "src/worker.js"
compatibility_date = "2025-06-30"

# nahraď vlastní doménou nebo subdoménou
route = "www.sledujkiki.com/*"

# žádné KV → blok kv_namespaces se maže
[observability.logs]
enabled = true
