# wrangler.toml

# Zvol si název, bude vidět v CF dashboardu. Musí být unikátní.
name = "muj-rozcestnik-worker" 
# Cesta k hlavnímu souboru Workeru
main = "src/index.js"       
# Datum pro zachování kompatibility s funkcemi Cloudflare
compatibility_date = "2024-06-30"
